import Foundation

/// Represents a source code file being generated.
///
/// `File` manages the generation of a single output file, including tracking imports/dependencies,
/// accumulating content, and writing the final file to disk with proper formatting.
///
/// Files are created and managed by `CodeBuildSession` during code generation.
public class File {
    /// Set of import/dependency identifiers needed by this file
    var imports: Set<String> = Set()

    /// The file system location where this file will be written
    var location: URL

    /// The file name
    var name: String

    /// The accumulated contents of the file
    var contents: String = ""

    /// Creates a new file.
    ///
    /// - Parameters:
    ///   - name: The file name (including extension)
    ///   - root: The root directory where the file will be created
    init(name: String, root: URL) {
        self.location = root.appending(path: name)
        self.name = name
    }

    /// Adds an import/dependency to this file.
    ///
    /// - Parameter val: The import identifier (e.g., package name, module name)
    public func depend(_ val: String) {
        self.imports.insert(val)
    }

    /// Appends content to the file.
    ///
    /// - Parameter val: The content to append
    public func append(_ val: String) {
        self.contents += val
    }

    /// Finalizes the file and writes it to disk.
    ///
    /// This method:
    /// 1. Resolves imports using the language implementation
    /// 2. Adds a generation comment header
    /// 3. Creates parent directories if needed
    /// 4. Writes the final content to disk
    ///
    /// - Parameter lang: The language implementation for resolving imports and comments
    /// - Throws: File I/O errors if directory creation or writing fails
    public func finalize(usingLanguage lang: Language) throws {
        let imports = lang.resolveImports(imports: Array(imports))
        let finalString = """
            \(lang.comment(for: "Generated by Passport. Do not modify."))
            \(lang.comment(for: "File generated at \(Date().formatted())"))
            \(imports)
            \(contents)
            """
        let exceptFinalPath = location.deletingLastPathComponent()
        if !FileManager.default.fileExists(atPath: exceptFinalPath.path) {
            try FileManager.default.createDirectory(at: exceptFinalPath, withIntermediateDirectories: true)
        }
        try finalString.write(to: location, atomically: true, encoding: .utf8)
    }
}
