name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.4.0
        with:
          swift-version: "6.2"

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.5'

      - name: Build library
        run: swift build --target Passport

      - name: Run Demo
        run: swift run

      - name: Build Go Generated code
        run: cd generated/go && go build .
